name: eightsteps_mobile
description: Offline-first personal finance app MVP.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  drift: ^2.31.0
  drift_flutter: ^0.2.5
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  path: ^1.9.1
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  uuid: ^4.5.1
  google_fonts: ^6.3.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.8.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/8steps.png
    - assets/images/logo.png
    - assets/images/mainbg.jpg
    - assets/images/loginbg.jpg
    - assets/images/registerbg.jpg
    - assets/images/loginbg.jpeg
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/8steps.png
  min_sdk_android: 21
